# minihawk_joint_position_controller:
#   type: position_controllers/JointTrajectoryController 
#   topic: "minihawk_joint_position"
#   joints:
#     #  - minihawk/MH_elevon_left_joint
#     #  - minihawk/MH_elevon_right_joint
#      - minihawk/MH_tilt_base_left_joint
#      - minihawk/MH_tilt_base_right_joint
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.5
#     #   minihawk/MH_elevon_left_joint: {trajectory: 0.1, goal: 0.1}
#     #   minihawk/MH_elevon_right_joint: {trajectory: 0.1, goal: 0.1}
#       minihawk/MH_tilt_base_left_joint: {trajectory: 0.1, goal: 0.1}
#       minihawk/MH_tilt_base_right_joint: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 20
#   gains:
#     #   minihawk/MH_elevon_left_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
#     #   minihawk/MH_elevon_right_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
#       minihawk/MH_tilt_base_left_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
#       minihawk/MH_tilt_base_right_joint: {p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1} #{p: 1.2,  i: 0.01, d: 0.1, i_clamp: 1}
#   velocity_ff:
#     #   minihawk/MH_elevon_left_joint: 1.0
#     #   minihawk/MH_elevon_right_joint: 1.0
#       minihawk/MH_tilt_base_left_joint: 1.0
#       minihawk/MH_tilt_base_right_joint: 1.0


# minihawk_joint_velocity_controller:
#   type: velocity_controllers/JointGroupVelocityController
#   topic: "minihawk_joint_velocity"
#   joints:
#      - minihawk/MH_motor_left_joint
#      - minihawk/MH_motor_right_joint
#      - minihawk/MH_motor_rear_joint
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.5
#       minihawk/MH_motor_left_joint: {trajectory: 0.1, goal: 0.1}
#       minihawk/MH_motor_right_joint: {trajectory: 0.1, goal: 0.1}
#       minihawk/MH_motor_rear_joint: {trajectory: 0.1, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 20
#   gains:
#       minihawk/MH_motor_left_joint: {p: 10.0,  i: 1.0, d: 1.0, i_clamp: 1.0} 
#       minihawk/MH_motor_right_joint: {p: 10.0,  i: 1.0, d: 1.0, i_clamp: 1.0} 
#       minihawk/MH_motor_rear_joint: {p: 10.0,  i: 1.0, d: 1.0, i_clamp: 1.0} 
#   velocity_ff:
#       minihawk/MH_motor_left_joint: 1.0
#       minihawk/MH_motor_right_joint: 1.0
#       minihawk/MH_motor_rear_joint: 1.0
